### ISSUE TITLE
Failed while using in fragment

### ISSUE THREAD

**Issue by virtual46** [astuetz/PagerSlidingTabStrip#240]
java.lang.NullPointerException: Attempt to write to field 'android.support.v4.app.FragmentManagerImpl android.support.v4.app.Fragment.mFragmentManager' on a null object reference
            at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:417)
            at android.support.v4.app.BackStackRecord.add(BackStackRecord.java:412)
            at android.support.v4.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:99)
            at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:869)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1019)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:18843)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
            at android.view.View.measure(View.java:18843)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.view.View.measure(View.java:18843)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:874)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
            at android.view.View.measure(View.java:18843)
            at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:868)
            at android.view.View.measure(View.java:18843)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:18843)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
            at android.view.View.measure(View.java:18843)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.view.View.measure(View.java:18843)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
            at android.view.View.measure(View.java:18843)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3072)
            at android.view.View.measure(View.java:18843)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2343)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1379)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1623)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6943)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
            at android.view.Choreographer.doCallbacks(Choreographer.java:590)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6837)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by theBlbDan** [comment]
This pretty much only signifies that you have a problem in your code, not PSTS.  You'll need to provide some context, code, etc.

I see you are using FragmentPagerAdapter.  I'm using FragmentStatePagerAdapter without any problems.

**Comment by ka05** [comment]
If you are using inside a Fragment try using the childFragmentManager() to instantiate your pager adapter.
