### ISSUE TITLE
after upgrade AndroidStudio3 + gradle3.0.0 throw java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12

### ISSUE THREAD

**Issue by hexi** [astuetz/PagerSlidingTabStrip#317]
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
  at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:666)
  at com.astuetz.PagerSlidingTabStrip.<init>(PagerSlidingTabStrip.java:148)
  at com.astuetz.PagerSlidingTabStrip.<init>(PagerSlidingTabStrip.java:106)
  at java.lang.reflect.Constructor.newInstance(Native Method) 
  at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
  at com.futures.appframework.BaseActivity.setContentView(BaseActivity.java:92) 
  at com.baidao.futures.module.message.MessageActivity.onCreate(MessageActivity.java:70)

**Comment by Crysis21** [comment]
This library is no longer updated for quite some time. I started working on an alternative lib which can be found here:
[https://github.com/Crysis21/PagerTabIndicator](https://github.com/Crysis21/PagerTabIndicator)

**Comment by lmh301** [comment]
I have the same issue

**Comment by maxouille** [comment]
Same here !

**Comment by eurycea** [comment]
I encountered this and migrated to TabLayout https://developer.android.com/reference/android/support/design/widget/TabLayout.html

For me it was as simple as changing the class and #setViewPager to #setupWithViewPager.

**Comment by yuxh3** [comment]
i have same issue ,How to solve it？

**Comment by zhuangdaoyuan** [comment]
![image](https://user-images.githubusercontent.com/11583318/40218553-454676ba-5aa4-11e8-96f5-e528dd3dd574.png)    I don't know why it must crash at here

**Comment by haomini** [comment]
still crash at here! @zhuangdaoyuan

**Comment by haomini** [comment]
![image](https://user-images.githubusercontent.com/21299300/40358580-4285e658-5df2-11e8-87ef-4d0ac9492089.png)
It looks like it has been fixed
