### ISSUE TITLE
NPE if there are no tabs to display

### ISSUE THREAD

**Issue by austynmahoney** [astuetz/PagerSlidingTabStrip#69]
The view throws an exception if there are no tabs available to display. It would be great if the view failed gracefully or gave a better error message.

### Test case ###
```java
mAdapter = new MyFragmentPagerAdapter(getChildFragmentManager());
Assert.assertTrue(mAdapter.size() == 0);
myViewPager.setAdapter(mAdapter);
tabStrip.setViewPager(myViewPager);
```
### Stack trace ###
```
java.lang.NullPointerException
        at com.astuetz.PagerSlidingTabStrip$PageListener.onPageScrolled(
                PagerSlidingTabStrip.java:361)
        at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1712)
        at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1633)
        at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:581)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1600)
        ...
```

**Comment by ayyb1988** [comment]
this problem had fixed?

**Comment by ray1984** [comment]
What is about fixing?

**Comment by IvanMurzak** [comment]
Same problem

**Comment by VasuDroid** [comment]
** I am facing Same Problem Can you tell us how do we fix this problem **

**Comment by ms03001620** [comment]
Same problem

`FATAL EXCEPTION: main
                                                               java.lang.NullPointerException
                                                                   at com.astuetz.PagerSlidingTabStrip$PageListener.onPageScrolled(PagerSlidingTabStrip.java:361)
                                                                   at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1839)`

**Comment by akshar100** [comment]
Why is this issue being closed without a comment ? Is it fixed or wontfix ?
